In [ ]:
print("pytorch Day-1 Fundamentals")

pytorch Day-1 Fundamentals


In [ ]:
!nvidia-smi

Sat Sep 17 11:03:50 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

1.12.1+cu113


##Tensors

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#to get tensors as python int
scalar.item()

7

In [ ]:
#creating vectors
vectors=torch.tensor([1,2])
print(vectors)

tensor([1, 2])


In [ ]:
vectors.ndim

1

In [ ]:

## matrix
matrix=torch.tensor([[1,2],
                      [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape ## shape of matrix

torch.Size([2, 2])

In [ ]:
## Tensor
tensor=torch.tensor([[[1,2,3,4],
                     [6,7,8,9],
                     [10,11,12,13]]])
tensor

tensor([[[ 1,  2,  3,  4],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape   # one 3 by 4 tensors

torch.Size([1, 3, 4])

## Random Tensors

In [ ]:
random_tensor= torch.randn(1,3,4)
random_tensor

tensor([[[-0.4735,  2.1079,  1.3185, -0.4394],
         [ 0.0438,  1.1840, -0.4585, -2.1017],
         [-0.1239,  2.4177,  0.0888,  0.4547]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([1, 3, 4])

## zeros and ones

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## creating ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## crating range of tensors and tensors-like

In [ ]:
rang=torch.arange(start=0,step=2,end=10)
print(rang)
rang[0]

tensor([0, 2, 4, 6, 8])


tensor(0)

In [ ]:
## creating tensors like
import time
start=time.time()
ten_like=torch.zeros_like(input=rang,device="cuda")
end=time.time()
print("Time taken :",end-start)
ten_like

Time taken : 3.9315993785858154


tensor([0, 0, 0, 0, 0], device='cuda:0')

##Tensor datatype

In [ ]:
import tracemalloc
tracemalloc.start()
float_16_tensors=torch.tensor([3.4,33,9.0],dtype=torch.float16,device="cuda")
float_16_tensors
print("memory used:", tracemalloc.get_traced_memory())
tracemalloc.stop()

memory used: (632, 10966)


In [ ]:
## float16 to float32 conversion
import tracemalloc
tracemalloc.start()
float_32_tensors=float_16_tensors.type(torch.float32)
float_32_tensors
print("memory used:", tracemalloc.get_traced_memory())  ## memory usage increases float32
tracemalloc.stop()

memory used: (650, 10984)


In [ ]:
float_16_tensors*float_32_tensors

tensor([  11.5627, 1089.0000,   81.0000], device='cuda:0')

#### Error

In [ ]:
int16_tensor=torch.tensor(1000000000000000000000000000,dtype=torch.int8) ## more then int8 range –9,223,372,036,854,775,807 to 9,223,372,036,854,775,807

RuntimeError: ignored

## size and shape

In [ ]:
tensor=torch.rand(size=(20,20),dtype=torch.float16,device="cuda",requires_grad=False)
print(f"shape of tensor: {tensor.shape}")
print(f"size of tensor: {tensor.size()}")   #shape and size functions rdoes the same job.only difference is size must be given as function
print(f"dtype of tensor: {tensor.dtype}")
print(f"dimension of tensor: {tensor.ndim}")
print(f"tensor device: {tensor.device}")

shape of tensor: torch.Size([20, 20])
size of tensor: torch.Size([20, 20])
dtype of tensor: torch.float16
dimension of tensor: 2
tensor device: cuda:0


## Manipulating Tensors (tensor operation)


*   Addition
*   subtraction
*   multiplication
*   Division

*   Matrix multiplication








In [ ]:

# create a tensor
add_tensor=torch.tensor(10)
add_tensor+10

tensor(20)

In [ ]:
sub_tensor=torch.tensor(1)
sub_tensor-20

tensor(-19)

In [ ]:
mul_tensor=torch.tensor(50)
mul_tensor*5

tensor(250)

In [ ]:
div_tensor=torch.tensor(5)
div_tensor/6

tensor(0.8333)

In [ ]:
%%time
tensor1=torch.tensor([[1,2,3],[3,4,5]])
tensor2=torch.tensor([[1,2],[4,5],[6,7]])
mat_mul=torch.matmul(tensor1,tensor2)
mat_mul

CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 7.63 ms


tensor([[27, 33],
        [49, 61]])

In [ ]:
%%time
tensor1 @ tensor2  ## does the job same as torch.matmul()

CPU times: user 642 µs, sys: 0 ns, total: 642 µs
Wall time: 490 µs


tensor([[27, 33],
        [49, 61]])

In [ ]:
torch.rand(size=(4,2)) @ torch.rand(size=(2,3))  ## The resulting matrix has the sahpe of the outer dimension (4,3)

tensor([[0.6489, 0.7026, 0.5582],
        [0.8041, 0.9491, 0.7652],
        [0.4392, 0.7931, 0.6750],
        [0.5012, 0.6705, 0.5508]])

## shape errors

In [ ]:
## shapes for matrix multiplication
tensor_a= torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_b= torch.tensor([[7,8],
                        [9,10],
                        [11,12]])
torch.mm(tensor_a,tensor_b) ## same as torch.matmul

RuntimeError: ignored


We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

1. ``torch.transpose(input, dim0, dim1)``- where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

2. ``tensor.T`` - where tensor is the desired tensor to transpose.

In [ ]:
tensor_a.shape,tensor_b.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
tensor_a @ tensor_b.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_a.shape}, tensor_B = {tensor_b.shape}\n")
print(f"New shapes: tensor_A = {tensor_a.shape} (same as above), tensor_B.T = {tensor_b.T.shape}\n")
print(f"Multiplying: {tensor_a.shape} * {tensor_b.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_a, tensor_b.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum etc..,

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
## Find the min and max
torch.min(x),torch.max(x)

(tensor(0), tensor(90))

In [ ]:
torch.mean(x)      ## dtype must not be long for torch.mean() function  

RuntimeError: ignored

In [ ]:
## Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
## find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
## finding max and min value index
import numpy as np
print(x[torch.argmax(x)].tolist(),torch.argmax(x),x,"--> method1")
print(np.argmax(x),"-->method2")

90 tensor(9) tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) --> method1
tensor(9) -->method2


In [ ]:
print(x[torch.argmin(x)].tolist(),torch.argmin(x),x,"--> method1")
print(np.argmin(x),"-->method2")

0 tensor(0) tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) --> method1
tensor(0) -->method2


## Reshaping, stacking, squeezing and unsqueezing

In [ ]:
import torch
x=torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
## add an extra dimension
x_reshaped=x.reshape(1,1,9)
x_reshaped.shape

torch.Size([1, 1, 9])

In [ ]:
## change the view
z=x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

### view: changing z changes x (because a view of a tensor shares the same memory as the orginal input)

In [ ]:
x[1]=34
print("x value:",x,"z value changed",z)

x value: tensor([ 1, 34,  3,  4,  5,  6,  7,  8,  9]) z value changed tensor([[ 1, 34,  3,  4,  5,  6,  7,  8,  9]])


In [ ]:
x_reshaped[0]

tensor([ 1, 34,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
## stack tensors on top of each other        ## dim=0 -> vstack,dim=1->hstack
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1, 34,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 34,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 34,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 34,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 1, 9])

In [ ]:
## torch.squeeze()-> removes all single dimensions from a target tensor
torch.squeeze(x_reshaped).shape  ## removes all single dimension

torch.Size([9])

In [ ]:
## torch.unsqeeze() -> adds a single dimension to a target tensor at a specific dimension
print(x_reshaped)         ## tensors have unlimited dimensions
print(x_reshaped.unsqueeze(dim=0).shape)
x_reshaped.unsqueeze(dim=0).ndim

tensor([[[ 1, 34,  3,  4,  5,  6,  7,  8,  9]]])
torch.Size([1, 1, 1, 9])


4

In [ ]:
## torch.permute- rearrange the dimension of a target tensor in a specified order
x_orginal= torch.rand(size=(224,224,3)) #[h,w,c]
#permute the orginal tensor to rearrange the axis (or dim) order
x_permuted=x_orginal.permute(2,0,1) # shifts axis 0->1,1->2,2->0
print(x_orginal.shape)
x_permuted.shape

torch.Size([224, 224, 3])


torch.Size([3, 224, 224])

In [ ]:
x_orginal[0,0,0]=10
x_permuted[0,0,0]

tensor(10.)

## indexing (selecting data from tensors)

In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0][0],x[0,0]  #both are same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
## index on moster inner backet
x[0,0,0],x[0][0][0]

(tensor(1), tensor(1))

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
## you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

## Pytorch tensors & Numpy

In [ ]:
## numpy array to tensors
import torch
import numpy as np

array=np.arange(1.,8.)
tensor=torch.from_numpy(array) ## warning : when converting from numpy-> pytorch reflects numpy's default datatype of float64 unless specifies otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
ten=torch.arange(1.,10.)
ten.dtype      ## pytorch default datatype float32

torch.float32

In [ ]:
array.dtype

dtype('float64')

In [ ]:
## tensor to numpy
tensor=torch.ones(3)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor        

(tensor([1., 1., 1.]), array([1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype  # replecates the tensor datatype not numpy default datatype(float64)

dtype('float64')

## random seed(Reproducibility)

In [ ]:
## crate two random tensors
random_tensor_a=torch.rand(3,4)
random_tensor_b=torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])
tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
## Let's make some random but reproducible tensors
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_a=torch.rand(3,4)
random_tensor_a.cuda()
torch.manual_seed(RANDOM_SEED)
random_tensor_b=torch.rand(3,4)
random_tensor_b.cuda()
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

In [1]:
## getting a GPU
import torch
torch.cuda.is_available()

True

In [2]:
# setup device agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
## count number of device
torch.cuda.device_count()

1

## putting tensors (and models) on the GPU

In [8]:
%%time
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu
CPU times: user 2.28 ms, sys: 63 µs, total: 2.34 ms
Wall time: 2.02 ms


In [9]:
%%time
## move tensor to GPU
tensor_on_gpu=tensor.to(device)
tensor_on_gpu


CPU times: user 0 ns, sys: 905 µs, total: 905 µs
Wall time: 1.32 ms


tensor([1, 2, 3], device='cuda:0')

## moving tensor back to the gpu

In [10]:
tensor_on_gpu.numpy()

TypeError: ignored

In [13]:
## to fix the error
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])