## 1. Create a random tensor with shape (7, 7)

In [9]:
import torch
rand_tensor_int=torch.randint(low=10,high=20,size=(7,7))
rand_tensor_float=torch.randn(size=(7,7))
print(rand_tensor_int)
print(rand_tensor_float)

tensor([[18, 18, 16, 10, 16, 15, 19],
        [14, 12, 10, 12, 13, 11, 14],
        [14, 19, 18, 14, 11, 18, 16],
        [18, 14, 12, 11, 10, 15, 10],
        [13, 13, 10, 18, 15, 11, 10],
        [11, 12, 10, 18, 17, 16, 12],
        [10, 13, 12, 14, 12, 19, 18]])
tensor([[-0.4028, -1.3405, -0.0057, -2.6673,  0.1679, -1.4204, -1.2846],
        [ 0.4196,  0.6297,  0.8288, -0.5560,  0.2653, -0.2120,  0.9214],
        [-0.2738,  0.8371,  0.9814, -0.4977, -0.2285,  0.2682,  1.0270],
        [-0.4414,  0.6227,  0.2868, -1.3299,  0.3991, -1.9632, -0.4154],
        [ 0.1458,  0.3734, -0.5356,  1.8017,  1.2818, -0.7733,  0.0060],
        [ 0.4961,  0.8714, -0.5031, -2.4717, -0.0743, -0.7044, -1.0760],
        [ 1.8377,  0.2173, -0.3217,  0.9411,  1.2608, -0.8483, -0.2921]])


##2 .Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7).

In [20]:
rand_tensor=torch.rand(size=(1,7))
tensor=torch.rand(size=(1,7))
rand_tensor @ tensor.T

tensor([[2.3652]])

## 3.Set the random seed to 0 

In [28]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
rand_tensor_1=torch.randn(size=(7,7),device="cuda:0")
torch.manual_seed(RANDOM_SEED)
rand_tensor_2=torch.randn(size=(7,7),device="cuda:0")
print(rand_tensor_1)
print(rand_tensor_2)
print(rand_tensor_1==rand_tensor_2)


tensor([[-0.9247, -0.4253, -2.6438,  0.1452, -0.1209, -0.5797, -0.6229],
        [-0.3284, -1.0745, -0.3631, -1.6711,  2.2655,  0.3117, -0.1842],
        [ 1.2866,  1.1820, -0.1271,  1.2169,  1.4353,  1.0605, -0.4941],
        [-1.4244, -0.7244, -1.2973,  0.0697, -0.0074,  1.8969,  0.6878],
        [-0.0779, -0.8373,  1.3506, -0.2879, -0.5965, -0.3283, -0.9086],
        [-0.8059, -0.7407, -0.0504,  0.5435,  1.5150,  0.0141,  0.4532],
        [ 1.6349,  0.7124, -0.1806,  1.0252, -1.4622, -0.7554, -0.1836]],
       device='cuda:0')
tensor([[-0.9247, -0.4253, -2.6438,  0.1452, -0.1209, -0.5797, -0.6229],
        [-0.3284, -1.0745, -0.3631, -1.6711,  2.2655,  0.3117, -0.1842],
        [ 1.2866,  1.1820, -0.1271,  1.2169,  1.4353,  1.0605, -0.4941],
        [-1.4244, -0.7244, -1.2973,  0.0697, -0.0074,  1.8969,  0.6878],
        [-0.0779, -0.8373,  1.3506, -0.2879, -0.5965, -0.3283, -0.9086],
        [-0.8059, -0.7407, -0.0504,  0.5435,  1.5150,  0.0141,  0.4532],
        [ 1.6349,  0.7124,

## 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [32]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [34]:
RANDOM_SEED=1234
torch.manual_seed(RANDOM_SEED)
rand_tensor_1=torch.randn(size=(7,7))
rand_tensor_1=rand_tensor_1.to(device)
torch.manual_seed(RANDOM_SEED)
rand_tensor_2=torch.randn(size=(7,7))
rand_tensor_2=rand_tensor_2.to(device)
print(rand_tensor_1)
print(rand_tensor_2)
print(rand_tensor_1==rand_tensor_2)
print(rand_tensor_1.device)
print(rand_tensor_2.device)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539,  0.6684, -0.0597],
        [-0.4675, -0.2153,  0.8840, -0.7584, -0.3689, -0.3424, -1.4020],
        [ 0.3206, -1.0219,  0.7988, -0.0923, -0.7049, -1.6024,  0.2891],
        [ 0.4899, -0.3853, -0.7120, -0.1706, -1.4594,  0.2207,  0.2463],
        [-1.3248,  0.6970, -0.6631,  1.2158, -1.4949, -0.0469, -1.5270],
        [-2.0143, -1.5173,  0.3877, -1.1849,  0.6897, -0.2833,  1.8169],
        [ 0.6808,  0.7244,  0.0323, -1.6593, -1.8773,  0.7372,  0.3910]],
       device='cuda:0')
tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539,  0.6684, -0.0597],
        [-0.4675, -0.2153,  0.8840, -0.7584, -0.3689, -0.3424, -1.4020],
        [ 0.3206, -1.0219,  0.7988, -0.0923, -0.7049, -1.6024,  0.2891],
        [ 0.4899, -0.3853, -0.7120, -0.1706, -1.4594,  0.2207,  0.2463],
        [-1.3248,  0.6970, -0.6631,  1.2158, -1.4949, -0.0469, -1.5270],
        [-2.0143, -1.5173,  0.3877, -1.1849,  0.6897, -0.2833,  1.8169],
        [ 0.6808,  0.7244,

## 5. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shap

In [38]:
RANDOM_SEED=7
torch.manual_seed(RANDOM_SEED)
rand_tensor_1=torch.rand(size=(1,1,1,10))
rand_tensor_2=rand_tensor_1.squeeze()
print(rand_tensor_1,rand_tensor_1.shape)
print(rand_tensor_2,rand_tensor_2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
